version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '${PORT}:${PORT}'
    environment:
      - PORT=${PORT}
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 120 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - redis:/data

volumes:
  redis:
    driver: local